# Generated by Django 5.2.4 on 2025-08-28 09:32

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('subtitle', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=500)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=store.models.upload_product_to_path)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('price_offert', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.producttype')),
            ],
        ),
    ]
