# Generated by Django 5.2.4 on 2025-08-28 12:40

import django.utils.timezone
import django_ckeditor_5.fields
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_producttype_alter_book_content_alter_book_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted',
            field=models.CharField(choices=[('yes', 'Yes'), ('not', 'Not')], default='not', max_length=3),
        ),
        
    ]
